#pragma once

#include <cstdint>
#include <vector>

namespace tachyon::text {

// Emergency fallback font data (Inter-Regular subset, ASCII 32-126)
// Generated by tools/generate_embedded_font.py
// This is a minimal 30KB subset for emergency fallback

static const std::uint8_t EMERGENCY_FALLBACK_FONT_DATA[] = {
    // Placeholder - run tools/generate_embedded_font.py to generate actual data
    // Format: bytes of a minimal TTF font subset
    0x00, 0x01, 0x00, 0x00, 0x00, 0x0C, 0x00, 0x80, 0x00, 0x03, 0x00, 0x70,
    // ... (actual font data will be generated by the script)
};

static const std::size_t EMERGENCY_FALLBACK_FONT_SIZE = sizeof(EMERGENCY_FALLBACK_FONT_DATA);

inline std::vector<std::uint8_t> get_emergency_fallback_font_data() {
    return std::vector<std::uint8_t>(
        EMERGENCY_FALLBACK_FONT_DATA,
        EMERGENCY_FALLBACK_FONT_DATA + EMERGENCY_FALLBACK_FONT_SIZE
    );
}

} // namespace tachyon::text
