# TachyonScene sources
set(TachyonSceneSources
    ${CMAKE_CURRENT_SOURCE_DIR}/core/scene/builder.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/core/scene/data_loader.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/core/scene/dependency_node.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/core/scene/evaluator.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/core/scene/evaluator_composition.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/core/scene/evaluator_math.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/core/scene/evaluator/camera2d_evaluator.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/core/scene/evaluator/hashing.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/core/scene/evaluator/layer_evaluator.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/core/scene/evaluator/layer_transform_3d.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/core/scene/evaluator/layer_utils.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/core/scene/evaluator/light_evaluator.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/core/scene/evaluator/mesh_animator.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/core/scene/evaluator/property_sampler.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/core/scene/evaluator/roi_calculator.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/core/scene/evaluator/templates.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/core/scene/rigging/constraint_solver.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/core/scene/rigging/ik_solver.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/core/scene/rigging/rig_graph.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/core/scene/state/evaluated_camera2d_state.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/core/spec/scene_spec_json.cpp
)
