# TachyonRenderer2D effects sources
set(TachyonRenderer2DEffectsSources
    ${CMAKE_CURRENT_SOURCE_DIR}/renderer2d/effects/blur/blur_effects.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/renderer2d/effects/color/chromatic_aberration.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/renderer2d/effects/color/color_effects.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/renderer2d/effects/effect_registry.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/renderer2d/effects/effect_resolver.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/renderer2d/effects/effect_blur_table.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/renderer2d/effects/effect_color_table.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/renderer2d/effects/effect_transition_table.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/renderer2d/effects/effect_distortion_table.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/renderer2d/effects/effect_generator_table.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/renderer2d/effects/effect_stylize_table.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/renderer2d/effects/core/effect_host.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/renderer2d/effects/core/effect_param_access.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/renderer2d/effects/core/glsl_transition_effect.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/renderer2d/effects/core/transitions/basic_transitions.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/renderer2d/effects/core/transitions/light_leak_transitions.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/renderer2d/effects/core/transitions/artistic_transitions.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/renderer2d/effects/core/utility_effects.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/renderer2d/effects/glitch.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/renderer2d/effects/distort/warp_stabilizer_effect.cpp
)
