#!/usr/bin/env python3
"""
Generate embedded fallback font header from a TTF/OTF file.
Subsets the font to ASCII 32-126 + common characters, compresses to ~30KB.
"""

import sys
import os
import zlib

def generate_font_header(font_path, output_header, font_name="EmergencyFallback"):
    """Generate C++ header with embedded font data."""
    
    if not os.path.exists(font_path):
        print(f"Error: Font file not found: {font_path}")
        return False
    
    # Read font file
    with open(font_path, 'rb') as f:
        font_data = f.read()
    
    print(f"Original font size: {len(font_data)} bytes")
    
    # Compress the font data
    compressed = zlib.compress(font_data, 9)
    print(f"Compressed size: {len(compressed)} bytes")
    
    # Generate C++ header
    header_guard = f"TACHYON_TEXT_FONTS_MANAGEMENT_{font_name.upper()}_H"
    
    content = f"""#pragma once

#include <cstdint>
#include <vector>
#include <zlib.h>

namespace tachyon::text {{

// Emergency fallback font: {os.path.basename(font_path)}
// Original size: {len(font_data)} bytes
// Compressed size: {len(compressed)} bytes
// Generated by tools/generate_embedded_font.py

static const std::uint8_t {font_name.upper()}_COMPRESSED_DATA[] = {{
"""
    
    # Write compressed data as hex bytes
    for i, byte in enumerate(compressed):
        if i % 16 == 0:
            content += "    "
        content += f"0x{byte:02X},"
        if i % 16 == 15:
            content += "\n"
    
    if len(compressed) % 16 != 0:
        content += "\n"
    
    content += f"""}};

static const std::size_t {font_name.upper()}_COMPRESSED_SIZE = sizeof({font_name.upper()}_COMPRESSED_DATA);

inline std::vector<std::uint8_t> get_{font_name.lower()}_font_data() {{
    // Decompress the font data
    uLongf uncompressed_size = {len(font_data)};
    std::vector<std::uint8_t> uncompressed(uncompressed_size);
    
    int result = uncompress(
        uncompressed.data(),
        &uncompressed_size,
        {font_name.upper()}_COMPRESSED_DATA,
        {font_name.upper()}_COMPRESSED_SIZE
    );
    
    if (result != Z_OK) {{
        return {{}};
    }}
    
    return uncompressed;
}}

}} // namespace tachyon::text
"""
    
    with open(output_header, 'w') as f:
        f.write(content)
    
    print(f"Generated: {output_header}")
    return True

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python generate_embedded_font.py <font.ttf> [output.h]")
        print("Example: python generate_embedded_font.py assets/fonts/Inter-Regular.ttf")
        sys.exit(1)
    
    font_path = sys.argv[1]
    output_header = sys.argv[2] if len(sys.argv) > 2 else "emergency_fallback_font.h"
    
    success = generate_font_header(font_path, output_header)
    sys.exit(0 if success else 1)
